import { Question, Difficulty } from './types';

let qid = 0;
const makeId = () => `q-${qid++}`;

// ========== EASY LEVEL: Basic vocabulary with pictures ==========
const easyQuestions: Question[] = [
  // Animals
  { id: makeId(), type: 'word-match', emoji: '🐱', prompt: 'What animal is this? 🐱', answer: 'CAT', options: ['CAT', 'DOG', 'FISH', 'BIRD'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Hewan apa ini? Ini adalah hewan yang suka bilang "meong"',
    speechText: 'What animal is this?' },
  { id: makeId(), type: 'word-match', emoji: '🐶', prompt: 'What animal is this? 🐶', answer: 'DOG', options: ['CAT', 'DOG', 'COW', 'PIG'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Hewan apa ini? Ini adalah hewan yang suka bilang "guk guk"',
    speechText: 'What animal is this?' },
  { id: makeId(), type: 'word-match', emoji: '🐟', prompt: 'What animal is this? 🐟', answer: 'FISH', options: ['FISH', 'BIRD', 'BEE', 'ANT'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Hewan apa ini? Ini adalah hewan yang hidup di air',
    speechText: 'What animal is this?' },
  { id: makeId(), type: 'word-match', emoji: '🐦', prompt: 'What animal is this? 🐦', answer: 'BIRD', options: ['FROG', 'BIRD', 'BEAR', 'BAT'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Hewan apa ini? Ini adalah hewan yang bisa terbang dan punya sayap',
    speechText: 'What animal is this?' },
  { id: makeId(), type: 'word-match', emoji: '🐸', prompt: 'What animal is this? 🐸', answer: 'FROG', options: ['FROG', 'FISH', 'FOX', 'FLY'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Hewan apa ini? Ini adalah hewan yang suka melompat dan bilang "kwok kwok"',
    speechText: 'What animal is this?' },
  { id: makeId(), type: 'word-match', emoji: '🐻', prompt: 'What animal is this? 🐻', answer: 'BEAR', options: ['DEER', 'BEAR', 'LION', 'WOLF'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Hewan apa ini? Dalam bahasa Indonesia namanya "beruang"',
    speechText: 'What animal is this?' },
  { id: makeId(), type: 'word-match', emoji: '🦁', prompt: 'What animal is this? 🦁', answer: 'LION', options: ['LION', 'TIGER', 'CAT', 'DOG'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Hewan apa ini? Ini adalah raja hutan! Dalam bahasa Indonesia: "singa"',
    speechText: 'What animal is this?' },
  { id: makeId(), type: 'word-match', emoji: '🐘', prompt: 'What animal is this? 🐘', answer: 'ELEPHANT', options: ['ELEPHANT', 'MOUSE', 'HORSE', 'ZEBRA'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Hewan apa ini? Ini hewan yang sangat besar dan punya belalai. Bahasa Indonesia: "gajah"',
    speechText: 'What animal is this?' },
  // Colors
  { id: makeId(), type: 'word-match', emoji: '🔴', prompt: 'What color is this? 🔴', answer: 'RED', options: ['RED', 'BLUE', 'GREEN', 'PINK'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Warna apa ini? Ini warna "merah"',
    speechText: 'What color is this?' },
  { id: makeId(), type: 'word-match', emoji: '🔵', prompt: 'What color is this? 🔵', answer: 'BLUE', options: ['RED', 'BLUE', 'PURPLE', 'BLACK'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Warna apa ini? Ini warna "biru", seperti langit',
    speechText: 'What color is this?' },
  { id: makeId(), type: 'word-match', emoji: '🟢', prompt: 'What color is this? 🟢', answer: 'GREEN', options: ['YELLOW', 'BLUE', 'GREEN', 'BROWN'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Warna apa ini? Ini warna "hijau", seperti daun',
    speechText: 'What color is this?' },
  { id: makeId(), type: 'word-match', emoji: '🟡', prompt: 'What color is this? 🟡', answer: 'YELLOW', options: ['ORANGE', 'YELLOW', 'GOLD', 'WHITE'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Warna apa ini? Ini warna "kuning", seperti matahari',
    speechText: 'What color is this?' },
  { id: makeId(), type: 'word-match', emoji: '🟠', prompt: 'What color is this? 🟠', answer: 'ORANGE', options: ['RED', 'YELLOW', 'ORANGE', 'BROWN'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Warna apa ini? Ini warna "oranye/jingga", seperti buah jeruk',
    speechText: 'What color is this?' },
  // Fruits
  { id: makeId(), type: 'word-match', emoji: '🍎', prompt: 'What fruit is this? 🍎', answer: 'APPLE', options: ['APPLE', 'GRAPE', 'MANGO', 'PEACH'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Buah apa ini? Ini buah "apel", warnanya merah dan rasanya manis',
    speechText: 'What fruit is this?' },
  { id: makeId(), type: 'word-match', emoji: '🍌', prompt: 'What fruit is this? 🍌', answer: 'BANANA', options: ['BANANA', 'LEMON', 'CORN', 'MANGO'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Buah apa ini? Ini buah "pisang", warnanya kuning dan bentuknya melengkung',
    speechText: 'What fruit is this?' },
  { id: makeId(), type: 'word-match', emoji: '🍊', prompt: 'What fruit is this? 🍊', answer: 'ORANGE', options: ['APPLE', 'ORANGE', 'PEACH', 'LEMON'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Buah apa ini? Ini buah "jeruk", rasanya asam manis',
    speechText: 'What fruit is this?' },
  { id: makeId(), type: 'word-match', emoji: '🍇', prompt: 'What fruit is this? 🍇', answer: 'GRAPE', options: ['GRAPE', 'BERRY', 'PLUM', 'FIG'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Buah apa ini? Ini buah "anggur", buahnya kecil-kecil bergerombol',
    speechText: 'What fruit is this?' },
  { id: makeId(), type: 'word-match', emoji: '🍓', prompt: 'What fruit is this? 🍓', answer: 'STRAWBERRY', options: ['STRAWBERRY', 'CHERRY', 'APPLE', 'TOMATO'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Buah apa ini? Ini buah "stroberi", warnanya merah dan ada biji-bijinya',
    speechText: 'What fruit is this?' },
  // Numbers
  { id: makeId(), type: 'word-match', emoji: '1️⃣', prompt: 'How do you say this number? 1️⃣', answer: 'ONE', options: ['ONE', 'TWO', 'TEN', 'SIX'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Bagaimana cara mengucapkan angka ini? Angka "satu" dalam bahasa Inggris',
    speechText: 'How do you say this number? One.' },
  { id: makeId(), type: 'word-match', emoji: '5️⃣', prompt: 'How do you say this number? 5️⃣', answer: 'FIVE', options: ['FOUR', 'FIVE', 'SIX', 'NINE'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Bagaimana cara mengucapkan angka ini? Angka "lima" dalam bahasa Inggris',
    speechText: 'How do you say this number? Five.' },
  // Body parts
  { id: makeId(), type: 'word-match', emoji: '👀', prompt: 'What body part is this? 👀', answer: 'EYES', options: ['EARS', 'EYES', 'NOSE', 'MOUTH'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Bagian tubuh apa ini? Ini adalah "mata", kita gunakan untuk melihat',
    speechText: 'What body part is this?' },
  { id: makeId(), type: 'word-match', emoji: '👃', prompt: 'What body part is this? 👃', answer: 'NOSE', options: ['NOSE', 'MOUTH', 'CHIN', 'HAND'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Bagian tubuh apa ini? Ini adalah "hidung", kita gunakan untuk mencium bau',
    speechText: 'What body part is this?' },
  { id: makeId(), type: 'word-match', emoji: '👄', prompt: 'What body part is this? 👄', answer: 'MOUTH', options: ['EAR', 'EYE', 'MOUTH', 'NOSE'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Bagian tubuh apa ini? Ini adalah "mulut", kita gunakan untuk makan dan berbicara',
    speechText: 'What body part is this?' },
  { id: makeId(), type: 'word-match', emoji: '✋', prompt: 'What body part is this? ✋', answer: 'HAND', options: ['FOOT', 'HAND', 'ARM', 'LEG'], difficulty: 'easy',
    indonesianHint: '🇮🇩 Bagian tubuh apa ini? Ini adalah "tangan", kita gunakan untuk memegang',
    speechText: 'What body part is this?' },
];

// ========== MEDIUM LEVEL: Fill in blanks, basic sentences ==========
const mediumQuestions: Question[] = [
  // Fill in the blank
  { id: makeId(), type: 'fill-blank', emoji: '📝', prompt: 'I ___ a student.', answer: 'AM', options: ['AM', 'IS', 'ARE', 'WAS'], hint: 'I ...', difficulty: 'medium',
    indonesianHint: '🇮🇩 "Saya ___ seorang murid." — Kata ganti "I" (saya) menggunakan "am"',
    speechText: 'I blank a student.' },
  { id: makeId(), type: 'fill-blank', emoji: '📝', prompt: 'She ___ a teacher.', answer: 'IS', options: ['AM', 'IS', 'ARE', 'BE'], hint: 'She ...', difficulty: 'medium',
    indonesianHint: '🇮🇩 "Dia (perempuan) ___ seorang guru." — Kata ganti "She" menggunakan "is"',
    speechText: 'She blank a teacher.' },
  { id: makeId(), type: 'fill-blank', emoji: '📝', prompt: 'They ___ playing.', answer: 'ARE', options: ['AM', 'IS', 'ARE', 'WAS'], hint: 'They ...', difficulty: 'medium',
    indonesianHint: '🇮🇩 "Mereka ___ sedang bermain." — Kata ganti "They" (mereka) menggunakan "are"',
    speechText: 'They blank playing.' },
  { id: makeId(), type: 'fill-blank', emoji: '📝', prompt: 'The cat ___ on the table.', answer: 'IS', options: ['AM', 'IS', 'ARE', 'BE'], difficulty: 'medium',
    indonesianHint: '🇮🇩 "Kucing itu ___ di atas meja." — Untuk satu benda/hewan gunakan "is"',
    speechText: 'The cat blank on the table.' },
  { id: makeId(), type: 'fill-blank', emoji: '📝', prompt: 'We ___ happy today.', answer: 'ARE', options: ['AM', 'IS', 'ARE', 'WAS'], difficulty: 'medium',
    indonesianHint: '🇮🇩 "Kita ___ senang hari ini." — Kata ganti "We" (kita) menggunakan "are"',
    speechText: 'We blank happy today.' },
  // Translate simple words
  { id: makeId(), type: 'translate', emoji: '📖', prompt: '"Buku" in English is...', answer: 'BOOK', options: ['BOOK', 'DESK', 'PEN', 'BAG'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa bahasa Inggris dari "Buku"? Benda yang kita baca untuk belajar',
    speechText: 'What is Buku in English?' },
  { id: makeId(), type: 'translate', emoji: '🪑', prompt: '"Meja" in English is...', answer: 'TABLE', options: ['CHAIR', 'TABLE', 'DOOR', 'WALL'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa bahasa Inggris dari "Meja"? Tempat kita meletakkan buku dan menulis',
    speechText: 'What is Meja in English?' },
  { id: makeId(), type: 'translate', emoji: '💺', prompt: '"Kursi" in English is...', answer: 'CHAIR', options: ['TABLE', 'CHAIR', 'SHELF', 'BED'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa bahasa Inggris dari "Kursi"? Tempat kita duduk',
    speechText: 'What is Kursi in English?' },
  { id: makeId(), type: 'translate', emoji: '💧', prompt: '"Air" in English is...', answer: 'WATER', options: ['FIRE', 'WATER', 'WIND', 'RAIN'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa bahasa Inggris dari "Air"? Cairan yang kita minum setiap hari',
    speechText: 'What is Air in English? It means water.' },
  { id: makeId(), type: 'translate', emoji: '🏠', prompt: '"Rumah" in English is...', answer: 'HOUSE', options: ['HOUSE', 'SCHOOL', 'PARK', 'SHOP'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa bahasa Inggris dari "Rumah"? Tempat kita tinggal bersama keluarga',
    speechText: 'What is Rumah in English?' },
  { id: makeId(), type: 'translate', emoji: '🏫', prompt: '"Sekolah" in English is...', answer: 'SCHOOL', options: ['HOUSE', 'SCHOOL', 'CHURCH', 'OFFICE'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa bahasa Inggris dari "Sekolah"? Tempat kita belajar bersama guru dan teman',
    speechText: 'What is Sekolah in English?' },
  { id: makeId(), type: 'translate', emoji: '👩', prompt: '"Ibu" in English is...', answer: 'MOTHER', options: ['FATHER', 'MOTHER', 'SISTER', 'AUNT'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa bahasa Inggris dari "Ibu"? Orang tua perempuan yang melahirkan kita',
    speechText: 'What is Ibu in English?' },
  { id: makeId(), type: 'translate', emoji: '👨', prompt: '"Ayah" in English is...', answer: 'FATHER', options: ['FATHER', 'MOTHER', 'UNCLE', 'SON'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa bahasa Inggris dari "Ayah"? Orang tua laki-laki kita',
    speechText: 'What is Ayah in English?' },
  // Spelling
  { id: makeId(), type: 'spelling', emoji: '✏️', prompt: 'Choose the correct spelling:', answer: 'BEAUTIFUL', options: ['BEAUTFUL', 'BEAUTIFUL', 'BEUTIFUL', 'BEAUTIFULL'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Pilih ejaan yang benar! Kata ini artinya "cantik/indah"',
    speechText: 'Choose the correct spelling. Beautiful.' },
  { id: makeId(), type: 'spelling', emoji: '✏️', prompt: 'Choose the correct spelling:', answer: 'ELEPHANT', options: ['ELEFANT', 'ELEPHENT', 'ELEPHANT', 'ELAPHANT'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Pilih ejaan yang benar! Kata ini artinya "gajah"',
    speechText: 'Choose the correct spelling. Elephant.' },
  { id: makeId(), type: 'spelling', emoji: '✏️', prompt: 'Choose the correct spelling:', answer: 'SCHOOL', options: ['SKOOL', 'SCHOOL', 'SCHOL', 'SCOOL'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Pilih ejaan yang benar! Kata ini artinya "sekolah"',
    speechText: 'Choose the correct spelling. School.' },
  { id: makeId(), type: 'spelling', emoji: '✏️', prompt: 'Choose the correct spelling:', answer: 'FRIEND', options: ['FREND', 'FREIND', 'FRIEND', 'FRIND'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Pilih ejaan yang benar! Kata ini artinya "teman"',
    speechText: 'Choose the correct spelling. Friend.' },
  // Opposites
  { id: makeId(), type: 'word-match', emoji: '↔️', prompt: 'What is the opposite of HOT?', answer: 'COLD', options: ['WARM', 'COLD', 'COOL', 'ICE'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa lawan kata dari HOT (panas)? Lawannya adalah "dingin"',
    speechText: 'What is the opposite of hot?' },
  { id: makeId(), type: 'word-match', emoji: '↔️', prompt: 'What is the opposite of BIG?', answer: 'SMALL', options: ['TINY', 'SMALL', 'SHORT', 'LOW'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa lawan kata dari BIG (besar)? Lawannya adalah "kecil"',
    speechText: 'What is the opposite of big?' },
  { id: makeId(), type: 'word-match', emoji: '↔️', prompt: 'What is the opposite of HAPPY?', answer: 'SAD', options: ['MAD', 'SAD', 'BAD', 'ANGRY'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa lawan kata dari HAPPY (senang)? Lawannya adalah "sedih"',
    speechText: 'What is the opposite of happy?' },
  { id: makeId(), type: 'word-match', emoji: '↔️', prompt: 'What is the opposite of DAY?', answer: 'NIGHT', options: ['DARK', 'NIGHT', 'MOON', 'SLEEP'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa lawan kata dari DAY (siang)? Lawannya adalah "malam"',
    speechText: 'What is the opposite of day?' },
  { id: makeId(), type: 'word-match', emoji: '↔️', prompt: 'What is the opposite of UP?', answer: 'DOWN', options: ['LOW', 'DOWN', 'UNDER', 'BACK'], difficulty: 'medium',
    indonesianHint: '🇮🇩 Apa lawan kata dari UP (atas)? Lawannya adalah "bawah"',
    speechText: 'What is the opposite of up?' },
];

// ========== HARD LEVEL: Complex sentences, grammar ==========
const hardQuestions: Question[] = [
  // Past tense
  { id: makeId(), type: 'fill-blank', emoji: '⏰', prompt: 'Yesterday, I ___ to school.', answer: 'WENT', options: ['GO', 'WENT', 'GOING', 'GONE'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Kemarin, saya ___ ke sekolah." — Ini kalimat masa lalu (past tense). GO → WENT',
    speechText: 'Yesterday, I blank to school.' },
  { id: makeId(), type: 'fill-blank', emoji: '⏰', prompt: 'She ___ a cake last night.', answer: 'MADE', options: ['MAKE', 'MADE', 'MAKING', 'MAKES'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Dia ___ kue tadi malam." — Ini masa lalu. MAKE → MADE (membuat)',
    speechText: 'She blank a cake last night.' },
  { id: makeId(), type: 'fill-blank', emoji: '⏰', prompt: 'They ___ the movie yesterday.', answer: 'WATCHED', options: ['WATCH', 'WATCHED', 'WATCHING', 'WATCHES'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Mereka ___ film kemarin." — Untuk past tense kata kerja biasa, tambahkan -ed. WATCH → WATCHED',
    speechText: 'They blank the movie yesterday.' },
  { id: makeId(), type: 'fill-blank', emoji: '⏰', prompt: 'He ___ his homework already.', answer: 'FINISHED', options: ['FINISH', 'FINISHED', 'FINISHING', 'FINISHES'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Dia sudah ___ PR-nya." — Kata "already" artinya sudah. FINISH → FINISHED',
    speechText: 'He blank his homework already.' },
  // Prepositions
  { id: makeId(), type: 'fill-blank', emoji: '📍', prompt: 'The book is ___ the table.', answer: 'ON', options: ['IN', 'ON', 'AT', 'BY'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Buku itu ___ meja." — ON = di atas (menyentuh permukaan), IN = di dalam, AT = di (lokasi)',
    speechText: 'The book is blank the table.' },
  { id: makeId(), type: 'fill-blank', emoji: '📍', prompt: 'She lives ___ Jakarta.', answer: 'IN', options: ['IN', 'ON', 'AT', 'TO'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Dia tinggal ___ Jakarta." — Untuk kota/negara gunakan IN (di dalam)',
    speechText: 'She lives blank Jakarta.' },
  { id: makeId(), type: 'fill-blank', emoji: '📍', prompt: 'We arrived ___ the airport.', answer: 'AT', options: ['IN', 'ON', 'AT', 'TO'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Kita sampai ___ bandara." — Untuk tiba di suatu tempat gunakan AT',
    speechText: 'We arrived blank the airport.' },
  // Complex translate
  { id: makeId(), type: 'translate', emoji: '🌍', prompt: '"Saya sedang belajar" in English:', answer: 'I AM STUDYING', options: ['I AM STUDYING', 'I WAS STUDY', 'I STUDY NOW', 'I DO STUDY'], difficulty: 'hard',
    indonesianHint: '🇮🇩 Terjemahkan "Saya sedang belajar". Kata "sedang" = AM + kata kerja-ING (Present Continuous)',
    speechText: 'Translate: Saya sedang belajar, into English.' },
  { id: makeId(), type: 'translate', emoji: '🌍', prompt: '"Dia pergi ke sekolah" in English:', answer: 'SHE GOES TO SCHOOL', options: ['SHE GO SCHOOL', 'SHE GOES TO SCHOOL', 'SHE GOING SCHOOL', 'SHE TO SCHOOL GO'], difficulty: 'hard',
    indonesianHint: '🇮🇩 Terjemahkan "Dia pergi ke sekolah". She + kata kerja ditambah -es/-s (Simple Present)',
    speechText: 'Translate: Dia pergi ke sekolah, into English.' },
  { id: makeId(), type: 'translate', emoji: '🌍', prompt: '"Mereka bermain bola" in English:', answer: 'THEY PLAY BALL', options: ['THEY PLAY BALL', 'THEY PLAYING BALL', 'THEM PLAY BALL', 'THEY BALL PLAY'], difficulty: 'hard',
    indonesianHint: '🇮🇩 Terjemahkan "Mereka bermain bola". THEY (mereka) + PLAY (bermain) + BALL (bola)',
    speechText: 'Translate: Mereka bermain bola, into English.' },
  // Comparative
  { id: makeId(), type: 'fill-blank', emoji: '📊', prompt: 'This house is ___ than that one.', answer: 'BIGGER', options: ['BIG', 'BIGGER', 'BIGGEST', 'MORE BIG'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Rumah ini lebih ___ dari yang itu." — Perbandingan: BIG → BIGGER (lebih besar). Tambahkan -er',
    speechText: 'This house is blank than that one.' },
  { id: makeId(), type: 'fill-blank', emoji: '📊', prompt: 'She is ___ student in class.', answer: 'THE SMARTEST', options: ['SMARTER', 'THE SMARTEST', 'MOST SMART', 'SMART'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Dia murid paling ___ di kelas." — Superlatif: SMART → THE SMARTEST (paling pintar)',
    speechText: 'She is blank student in class.' },
  // Articles
  { id: makeId(), type: 'fill-blank', emoji: '📄', prompt: 'I saw ___ elephant at the zoo.', answer: 'AN', options: ['A', 'AN', 'THE', 'SOME'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Saya melihat ___ gajah di kebun binatang." — Gunakan AN sebelum huruf vokal (a,i,u,e,o). Elephant dimulai huruf E',
    speechText: 'I saw blank elephant at the zoo.' },
  { id: makeId(), type: 'fill-blank', emoji: '📄', prompt: '___ sun rises in the east.', answer: 'THE', options: ['A', 'AN', 'THE', 'THIS'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "___ matahari terbit di timur." — Gunakan THE untuk benda yang sudah diketahui/hanya satu (matahari)',
    speechText: 'Blank sun rises in the east.' },
  // Pronouns
  { id: makeId(), type: 'fill-blank', emoji: '👤', prompt: 'This book belongs to ___. (saya)', answer: 'ME', options: ['I', 'ME', 'MY', 'MINE'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "Buku ini milik ___." — Setelah kata depan (to), gunakan ME bukan I. I = subjek, ME = objek',
    speechText: 'This book belongs to blank.' },
  { id: makeId(), type: 'fill-blank', emoji: '👤', prompt: '___ is my best friend. (dia perempuan)', answer: 'SHE', options: ['SHE', 'HER', 'HERS', 'HIS'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "___ adalah sahabat saya." (dia perempuan) — SHE = dia (subjek), HER = dia (objek)',
    speechText: 'Blank is my best friend.' },
  // Question words
  { id: makeId(), type: 'fill-blank', emoji: '❓', prompt: '___ is your name?', answer: 'WHAT', options: ['WHAT', 'WHO', 'WHERE', 'WHEN'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "___ namamu?" — WHAT = apa, WHO = siapa, WHERE = dimana, WHEN = kapan',
    speechText: 'Blank is your name?' },
  { id: makeId(), type: 'fill-blank', emoji: '❓', prompt: '___ do you live?', answer: 'WHERE', options: ['WHAT', 'WHO', 'WHERE', 'WHEN'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "___ kamu tinggal?" — WHERE = di mana (menanyakan tempat)',
    speechText: 'Blank do you live?' },
  { id: makeId(), type: 'fill-blank', emoji: '❓', prompt: '___ old are you?', answer: 'HOW', options: ['HOW', 'WHAT', 'WHO', 'WHY'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "___ umurmu?" — HOW OLD = berapa umur. HOW = bagaimana/berapa',
    speechText: 'Blank old are you?' },
  { id: makeId(), type: 'fill-blank', emoji: '❓', prompt: '___ is your birthday?', answer: 'WHEN', options: ['WHAT', 'WHERE', 'WHEN', 'WHO'], difficulty: 'hard',
    indonesianHint: '🇮🇩 "___ ulang tahunmu?" — WHEN = kapan (menanyakan waktu)',
    speechText: 'Blank is your birthday?' },
];

export function getQuestions(difficulty: Difficulty): Question[] {
  const pool = difficulty === 'easy' ? easyQuestions : difficulty === 'medium' ? mediumQuestions : hardQuestions;
  // Shuffle and return
  return [...pool].sort(() => Math.random() - 0.5);
}

export function getDifficultyConfig(difficulty: Difficulty) {
  switch (difficulty) {
    case 'easy':
      return {
        label: 'Mudah',
        sublabel: 'Easy',
        description: 'Kosakata dasar dengan gambar',
        emoji: '⭐',
        color: 'from-green-400 to-emerald-500',
        bgColor: 'bg-green-100',
        textColor: 'text-green-700',
        timePerQuestion: 30,
        pointsPerCorrect: 10,
        lives: 5,
        streakBonus: 5,
      };
    case 'medium':
      return {
        label: 'Sedang',
        sublabel: 'Medium',
        description: 'Kalimat sederhana & terjemahan',
        emoji: '⭐⭐',
        color: 'from-yellow-400 to-orange-500',
        bgColor: 'bg-yellow-100',
        textColor: 'text-yellow-700',
        timePerQuestion: 30,
        pointsPerCorrect: 20,
        lives: 4,
        streakBonus: 10,
      };
    case 'hard':
      return {
        label: 'Sulit',
        sublabel: 'Hard',
        description: 'Tata bahasa & kalimat kompleks',
        emoji: '⭐⭐⭐',
        color: 'from-red-400 to-pink-500',
        bgColor: 'bg-red-100',
        textColor: 'text-red-700',
        timePerQuestion: 30,
        pointsPerCorrect: 30,
        lives: 3,
        streakBonus: 15,
      };
  }
}
